=== sticktgt/service/config/schema3.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "chart": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "version",
                "description"
            ]
        },
        "subjectArea": {
            "type": "string"
        },
        "sourceMetafileRepo": {
            "type": "string",
            "format": "uri"
        },
        "sourceMetafileBranch": {
            "type": "string"
        },
        "sourceMetafileName": {
            "type": "string"
        },
        "namespace": {
            "type": "string"
        },
        "environment": {
            "type": "string"
        },
        "image": {
            "type": "string"
        },
        "command": {
            "type": "string"
        },
        "args": {
            "type": "string"
        },
        "schedule": {
            "type": "string"
        },
        "startingDeadlineSeconds": {
            "type": "integer"
        },
        "concurrencyPolicy": {
            "type": "string",
            "enum": [
                "Allow",
                "Forbid",
                "Replace"
            ]
        },
        "successfulJobsHistoryLimit": {
            "type": "integer"
        },
        "failedJobsHistoryLimit": {
            "type": "integer"
        },
        "backoffLimit": {
            "type": "integer"
        },
        "deploymentName": {
            "type": "string"
        },
        "metadata": {
            "type": "object",
            "properties": {
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            },
            "required": [
                "labels"
            ]
        },
        "volumeMounts": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "mountPath": {
                        "type": "string"
                    }
                },
                "required": [
                    "name",
                    "mountPath"
                ]
            }
        },
        "volumes": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "emptyDir": {
                        "type": "object",
                        "properties": {
                            "medium": {
                                "type": "string"
                            },
                            "sizeLimit": {
                                "type": "string"
                            }
                        },
                        "additionalProperties": false
                    }
                },
                "required": [
                    "name"
                ]
            }
        },
        "deploy": {
            "type": "object",
            "properties": {
                "env": {
                    "type": "object",
                    "additionalProperties": true
                }
            },
            "required": [
                "env"
            ]
        },
        "code": {
            "type": "object",
            "properties": {
                "env": {
                    "type": "object",
                    "additionalProperties": true
                }
            },
            "required": [
                "env"
            ]
        }
    },
    "required": [
        "chart",
        "subjectArea",
        "sourceMetafileRepo",
        "sourceMetafileBranch",
        "sourceMetafileName",
        "namespace",
        "environment",
        "schedule",
        "image",
        "command",
        "args",
        "deploy",
        "code"
    ],
    "additionalProperties": false
}

=== sticktgt/service/config/values3.json
{
    "environment": "TEST",
    "chart": {
        "name": "test-cron-job",
        "version": "0.1.0",
        "description": "Test cronJob deployment chart"
    },
    "deploymentName": "test-cron-job",
    "namespace": "app-fdd",
    "metadata": {
        "labels": {
            "components": "cronjob-readservice",
            "entity": "readservice"
        }
    },
    "subjectArea": "readservice-test-project",
    "sourceMetafileName": "meta-job-document-loader",
    "sourceMetafileRepo": "https://neogit.neoflex.ru/vsemenov/tservice/",
    "sourceMetafileBranch": "main",
    "startingDeadlineSeconds": 30,
    "image": "readservice:latest",
    "schedule": "*/10 * * * *",
    "command": "[\"/bin/bash\"]",
    "args": "[\"-c\", \"python -m readservice.main\"]",
    "successfulJobsHistoryLimit": 2,
    "failedJobsHistoryLimit": 2,
    "concurrencyPolicy": "Forbid",
    "backoffLimit": 1,
    "code": {
        "env": {
            "embedding": {
                "provider": {
                    "value": "yandexGPT"
                }
            },
            "sources": {
                "use_local": {
                    "value": "true"
                },
                "use_s3": {
                    "value": "true"
                }
            },
            "storage": {
                "store_type": {
                    "value": "milvus"
                }
            },
            "delete_old_vectors": {
                "value": "true"
            }
        }
    },
    "deploy": {
        "env": {
            "embedding": {
                "yandexGPT": {
                    "api_key": {
                        "valueFrom": {
                            "secretKeyRef": {
                                "name": "readservice-secrets",
                                "key": "yandex-api-key"
                            }
                        }
                    },
                    "folder_id": {
                        "valueFrom": {
                            "secretKeyRef": {
                                "name": "readservice-secrets",
                                "key": "yandex-folder-id"
                            }
                        }
                    }
                }
            },
            "storage": {
                "milvus": {
                    "url": {
                        "value": "http://172.17.0.1:19530"
                    }
                }
            }
        }
    },
    "volumeMounts": [
        {
            "name": "local-docs",
            "mountPath": "/app/local_docs"
        }
    ],
    "volumes": [
        {
            "name": "local-docs",
            "hostPath": {
                "path": "/home/stickt/python/local_docs",
                "type": "Directory"
            }
        }
    ]
}
